---
title: Uebungsblatt 05
author: Truong (Hoang Tung Truong), Testfran (Minh Kien Nguyen), Hamdash
output: pdf_document
header-includes:
   - \usepackage{amssymb, diagbox}
---

## Aufgabe 1
a. $(a^+ + b^+ a^*)(b + bba^+)^*$
b. $a^* (ba^* + bb^+ a)^*$
c. $(b^* ab^* ab^* ab^* ab^* ab^* )^*$

## Aufgabe 2
a. Behauptung: $L_1$ ist nicht regulär, also

$L_1 = \{a^m$ $|$ $m > 0$ ist ein Quadratzahl $\}$ ist nicht durch endlichen Automaten erkennbar.

  - Angenommen, $L_1$ wäre regulär. Dann gäbe es ein $k$ wie im Pumping Lemma. Jeder k-große ($|w| \geq k$) Wort $w \in L_1$ hätte im k-vorderen Bereich ($|xy| \leq k$) ein nichtleere Teilwort $y$, das sich "aufpumpen" lässt.
  - Mit dem $k$ von oben betracten wir jetzt das Wort $w=(a^k)^k$
  1. Es ist in $L_1$
  2. Es ist k-gross ($|w| \ k^2 \geq k$)
  - Es müsst im k-vorderen Bereich ein Teilwort haben, das sich aufpumpen lässt. Aber wenn wir einen nichtleeren Teil $y$ aufpumpen bekommen wir ein neues Wort $w^{'}$, dessen Länge $|w^{'}|$ keine Quadratzahl ist.

Spezifischer: $|w| = k^2$

Das Wort mit der kleisten Länge, die aber größer als $k^2$ ist, ist $w_0 = (a^{(k+1)})^{k+1}$

mit $|w_0| = (k+1)^2 = k^2 + 2k +1$

Da $0 < |y| \leq k$ gilt $|w^{'}| = k^2 + |y| \leq k^2 + k < k^2 +2k +1$, also $w^{'} \notin L_1$. Widerspruch!

Es gibt daher keinen endlichen Automaten $A$ mit $L_1 = L(A)$.

Daraus folgt: $L_1$ ist nicht regulär. $\Box$

b. $L = \{a^n b^n| n \in \mathbb{N} \land n > 0\}$

Äquivalenzklassen von $L_2 = \{a^n b^n | n \in \mathbb{N} \land n > 0\}$

-  $[\epsilon] = \{\epsilon\}, [a] = \{a\}, [aa] = \{aa\}, ..., [a^k] = \{a^k\} (k \in \mathbb{N})$

- $[ab] = \{ab, a^2 b^2, ...\}, [a^2 b] = \{a^2 b, a^3 b ^2, a^4 b^3,...\},$

  $[a^3 b] = \{a^3 b,a^4 b^2, a^5 b^3,...\}, ..., [a^k b] = \{ a^{k+i-1} b^i|i \geq 1\} (k\in \mathbb{N})$

- $\Sigma^* - L_2$ mit $\Sigma = \{a,b\} = \{bx, a^n b^m, xbay$ $|$ $x,y \in \Sigma^* \land n,m \in \mathbb{N} \land m > n\}$

## Aufgabe 3
a.
- Automat A hat keine nicht erreichbaren Zustände.
- $\Sigma_A = \{a,b\}, F = \{q_2, q_5, q_6\}, Q-F = \{q_0, q_1, q_3, q_4\}$
- Wir beginnen damit, in der tabelle die Paare zu markieren, bei denen einer in F ist und der andere nicht.

\begin{tabular}{c|c|c|c|c|c|c|c}
  &$q_0$& $q_1$ & $q_2$ & $q_3$ & $q_4$ & $q_5$ & $q_6$ \\ \hline
0 &\diagbox{}{}&   & x &   &   & x & x \\ \hline
1 &\diagbox{}{}&\diagbox{}{}& x &   &   & x & x \\ \hline
2 &\diagbox{}{}&\diagbox{}{}&\diagbox{}{}& x & x &   &   \\ \hline
3 &\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&   & x & x \\ \hline
4 &\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}& x & x \\ \hline
5 &\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&   \\ \hline
6 &\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}
\end{tabular}
- Als nächstes wählen wir $e := a \in \Sigma_A$ und markieren alle  $(q_i, q_j)$ $(i<j)$ für die $(\sigma(q_i,e), \sigma (q_j,e))$ schon markiert ist
\begin{tabular}{c|c|c|c|c|c|c|c}
  &$q_0$& $q_1$ & $q_2$ & $q_3$ & $q_4$ & $q_5$ & $q_6$ \\ \hline
0 &\diagbox{}{}&   & x &   &   & x & x \\ \hline
1 &\diagbox{}{}&\diagbox{}{}& x &   &   & x & x \\ \hline
2 &\diagbox{}{}&\diagbox{}{}&\diagbox{}{}& x & x &\textbf{x}&\textbf{x} \\ \hline
3 &\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&   & x & x \\ \hline
4 &\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}& x & x \\ \hline
5 &\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&   \\ \hline
6 &\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}&\diagbox{}{}
\end{tabular}

b.

## Aufgabe 1

